baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 10

[markup]
  [markup.tableOfContents]
    startLevel = 0
    endLevel = 5
    ordered = false

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 3
  showReadingTime = true
  toc = true
  

[languages]
  [languages.en]
    [languages.en.params.logo]
      logoText = "k0rventen:~"
      logoHomeLink = "/"
      title = ""
      subtitle = ""
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      writtenBy = ""
      readMore = "read more"
      readOtherPosts = "read other posts"
      lastModDisplay = "updated"
      newerPosts = "newer posts"
      olderPosts = "older posts"
      minuteReadingTime = "min read"
      dateFormatSingle = "2006-01-02"
      dateFormatList = "2006-01-02"
      
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "posts"
        url = "/"

      [[languages.en.menu.main]]
        identifier = "manpage"
        name = "manpage"
        url = "/manpage"

